routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'FrontController@home')->name('typeservices');
Route::get('/workshop', 'FrontController@workshop')->name('workshop');
Route::get('/edu', 'FrontController@edu')->name('edu');
Route::get('/blog', 'FrontController@blogindex')->name('blog.index');
Route::get('/blog/{slug}', 'FrontController@blogpost')->name('blog.post');
Route::get('/blog/tag/{slug}', 'FrontController@blogtag')->name('blog.tag');

//AJAX
Route::post('mailmkt', 'MailmktController@add');

Auth::routes();

Route::group(
    [
        'prefix'     => 'admin',
        'middleware' => ['auth'],
        'namespace'  => '\App\Http\Controllers',
    ], function () {

        Route::resource('roles', 'RoleController')->middleware(['role:admin']);
        Route::resource('users', 'UserController')->middleware(['role:admin']);

        Route::get('home', 'HomeController@index')->name('home')->middleware(['permission:dashboard']);;

        Route::resource('blogpost', 'BlogpostController');
        Route::resource('mailmkt', 'MailmktController');
        Route::resource('tag', 'TagController');

    }
);

resources/views/admin/inc/leftmenu.blade.php
<!-- Sidebar Menu -->
<nav class="mt-2">
    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
        <li class="nav-item">
            <a href="{{ route('home')}}" class="nav-link">
                <i class="nav-icon fas fa-tachometer-alt"></i>
                <p>Dashboard</p>
            </a>
        </li>
        <li class="nav-item">
            <a href="{{ route('blogpost.index')}}" class="nav-link">
                <i class="nav-icon fas fa-blog"></i>
                <p>Blog Posts</p>
            </a>
        </li>
        <li class="nav-item">
            <a href="{{ route('mailmkt.index')}}" class="nav-link">
                <i class="nav-icon fas fa-mail-bulk"></i>
                <p>e-Mails</p>
            </a>
        </li>
        <li class="nav-item">
            <a href="{{ route('tag.index')}}" class="nav-link">
                <i class="nav-icon fas fa-tag"></i>
                <p>Tags</p>
            </a>
        </li>
        @can('admin')
            <li class="nav-item">
                <a href="{{ route('users.index') }}" class="nav-link">
                    <i class="nav-icon fas fa-user"></i>
                    <p>Users</p>
                </a>
            </li>
            <li class="nav-item">
                <a href="{{ route('roles.index') }}" class="nav-link">
                    <i class="nav-icon fas fa-user-tag"></i>
                    <p>Roles/Permissions</p>
                </a>
            </li>
            <li class="nav-item">
                <a href="/log-viewer" class="nav-link" target="_blank">
                    <i class="nav-icon fas fa-bug"></i>
                    <p>Logs</p>
                </a>
            </li>
        @endcan
    </ul>
</nav>
<!-- /.sidebar-menu -->